DIMM association correction in 1S4U config json
ibm-openbmc/phosphor-led-manager pull request #12
Opened 2022-04-20 08:32 UTC by PriyangaRamasamy

The led group associations for dimms was pointing to incorrect
dimm inventory paths in rainier 1s4u led config json.
This commit has the correction in all the dimm association entries.

Signed-off-by: Priyanga Ramasamy <priyanga24@in.ibm.com>

2022-04-20 08:34 UTC, PriyangaRamasamy commented
The correct/updated 1s4u vpd inventory json is present here https://github.ibm.com/openbmc/openbmc/pull/2269

2022-04-21 03:28 UTC, jinuthomas requested changes
Why this change is done?

2022-04-21 03:52 UTC, PriyangaRamasamy commented
@jinuthomas Without my change, 1s4u led config json was having ddimm0_fault , ddimm0_identify , ddimm1_fault, ...... till ddimm7_fault as led groups which are pointing to incorrect dimm associations ( rainier 4u association json to match with ) 
 ( https://github.ibm.com/openbmc/openbmc/blob/1020-ghe/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/p10bmc/ibm%2Crainier-4u_associations.json ).

As per rainier workbook, (P0-C12, C13, C207, C32, C28, C29, C31, C30 ) these are the valid dimm location codes for 1s4u system. I made the led config json to point to the right association based on the above mentioned location code.

Please refer these 3 files,  #12 , https://github.ibm.com/openbmc/openbmc/pull/2269 and https://github.ibm.com/openbmc/openbmc/blob/1020-ghe/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/p10bmc/ibm%2Crainier-4u_associations.json and cross check with the above mentioned dimm location codes.

2022-04-21 05:16 UTC, jinuthomas approved these changes
OK , did not know which issue this was.

2022-04-21 12:50 UTC, merged