Addition of led group config for Bonnell system
ibm-openbmc/phosphor-led-manager pull request #16
Opened 2022-09-16 12:05 UTC by GiridhariKrishna

Don't have RDX, as it was not there upstream, please comment if need to add.

2022-10-10 05:26 UTC, jinuthomas requested changes

2022-10-10 05:26 UTC, jinuthomas commented on configs/ibm,bonnell/led-group-config.json
> +         "group" : "enclosure_identify",
All should be ON and not black for enclosure identify

2023-01-31 03:38 UTC, jinuthomas requested changes
this is not correct

2023-01-31 21:39 UTC, geissonator commented
add to approvelist

2023-02-28 14:23 UTC, closed without merging