Handing partition SA / platform SA
ibm-openbmc/phosphor-led-manager pull request #2
Opened 2021-12-27 10:14 UTC by lxwinspur

Signed-off-by: George Liu <liuxiwei@inspur.com>

2022-01-17 10:18 UTC, santoshpuranik commented
Codewise this looks good to me. I need to get this on a system and test. I plan to do that this week, will approve once my testing looks good.

2022-01-17 10:20 UTC, lxwinspur commented
> 

Ack

2022-01-17 13:27 UTC, jinuthomas approved these changes

2022-01-27 07:56 UTC, santoshpuranik requested changes
Finally got a chance to test this. Some changes are needed based on my testing.

2022-01-27 07:56 UTC, santoshpuranik commented on ibm-sai.cpp
> +                "Functional", functionalValue);
The use case here is actually slightly different - We have two LED group objects, the PLATFORM_SAI and PARTITION_SAI pointing to the same inventory object (See https://github.com/openbmc/openbmc/blob/a2cc401d586a9b1a3cdf2e93847839b551b48074/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/p10bmc/ibm%2Ceverest_associations.json#L293).

So when setting Operational status to true, we need to sure that both groups are de-asserted.

If we are setting OperationalStatus to true, it is OK to just look at the asserted for the incoming path.

2022-02-04 09:26 UTC, santoshpuranik commented
I created #3 by fixing the issues I found when testing this PR. I think we can continue the review there. This can be closed.

2022-02-08 01:16 UTC, lxwinspur commented on ibm-sai.cpp
> +    if (path != PARTITION_SAI || path != PLATFORM_SAI)
Done

2022-02-08 01:16 UTC, lxwinspur commented on ibm-sai.cpp
> +    std::string fru = path + "/fault_led_group";
Done

2022-02-10 12:55 UTC, lxwinspur commented
> 

Sure, I will close it

2022-02-10 12:55 UTC, closed without merging