meson_options.txt: Support for reading options from meson.options
ibm-openbmc/phosphor-led-manager pull request #58
Opened 2024-01-04 16:08 UTC by GiridhariKrishnan

Support has been added for reading options from meson.options instead of meson_options.txt[1]. These are equivalent, but not using the .txt extension for a build file has a few advantages, chief among them many tools and text editors expect a file with the .txt extension to be plain text files, not build scripts.

[1] https://mesonbuild.com/Release-notes-for-1-1-0.html#support-for-reading-options-from-mesonoptions

Change-Id: Icf7286351b49c526d02327e3a2d72c40b5f9a960

2024-01-04 20:05 UTC, geissonator commented
add to approvelist

2024-01-05 05:50 UTC, jinuthomas approved these changes

2024-01-05 06:54 UTC, SunnySrivastava1984 requested changes
Please remove merge conflicts.

2024-01-10 07:01 UTC, SunnySrivastava1984 approved these changes

2024-01-22 07:43 UTC, Alpana07 approved these changes

2024-01-23 04:14 UTC, jinuthomas approved these changes

2024-01-23 04:14 UTC, merged