leds:Make use of Decorator.Compatible interface
ibm-openbmc/phosphor-led-manager pull request #70
Opened 2024-06-17 14:06 UTC by Alpana07

Switching led-manager to use xyz.openbmc_project.Inventory.Decorator. Compatible interface from using xyz.openbmc_project.Configuration. IBMCompatibleSystem interface.

Test:
Tested for right config json is picked based on the Names property from xyz.openbmc_project.Inventory.Decorator.Compatible interface.

./phosphor-ledmanager
Inside getFilePath
Get the NAME based json
"/usr/share/phosphor-led-manager/com.ibm.Hardware.Chassis.Model.Rainier4U.json" is selected for config file

where,
busctl Get on "xyz.openbmc_project.Inventory.Decorator.Compatible"  "Names" results as-
v as 2 "com.ibm.Hardware.Chassis.Model.Rainier4U" "com.ibm.Hardware.Chassis.Model.Rainier"

Change-Id: I48ee37cb3f11fd6cd99e913caee4ebeb2e1004c3

2024-06-18 07:04 UTC, PriyangaRamasamy requested changes
you should rename the json files from configs/ibm-blueridge-1s4u/led-group-config.json to configs/com.ibm.Hardware.Chassis.Model.Blueridge1S4U.json.

Perform move operation instead of copy here.

2024-06-27 06:39 UTC, Alpana07 commented
> you should rename the json files from configs/ibm-blueridge-1s4u/led-group-config.json to configs/com.ibm.Hardware.Chassis.Model.Blueridge1S4U.json.
> 
> Perform move operation instead of copy here.

But I think we need old files also, as per the code.
It is looking for "led-group-config.json" in /etc/ path and /usr/share/ path. If not found there then it goes for Names.json

2024-07-09 11:25 UTC, PriyangaRamasamy commented
may I know the reason why you removed the file name changes

2024-07-09 11:38 UTC, PriyangaRamasamy commented
> > you should rename the json files from configs/ibm-blueridge-1s4u/led-group-config.json to configs/com.ibm.Hardware.Chassis.Model.Blueridge1S4U.json.
> > Perform move operation instead of copy here.
> 
> But I think we need old files also, as per the code. It is looking for "led-group-config.json" in /etc/ path and /usr/share/ path. If not found there then it goes for Names.json

The led_group_config.json present in /etc/path and /usr/share/path are the default jsons. When the JSON is picked based on device tree model, the code expects the json file name in this pattern configs/com.ibm.Hardware.Chassis.Model.Blueridge1S4U.json.

below are the lines:
>auto configFileName = name + ".json";
>auto configFilePath = fs::path{confBasePath} / configFileName;

2024-07-09 11:49 UTC, Alpana07 commented
> > > you should rename the json files from configs/ibm-blueridge-1s4u/led-group-config.json to configs/com.ibm.Hardware.Chassis.Model.Blueridge1S4U.json.
> > > Perform move operation instead of copy here.
> > 
> > 
> > But I think we need old files also, as per the code. It is looking for "led-group-config.json" in /etc/ path and /usr/share/ path. If not found there then it goes for Names.json
> 
> The led_group_config.json present in /etc/path and /usr/share/path are the default jsons. When the JSON is picked based on device tree model, the code expects the json file name in this pattern configs/com.ibm.Hardware.Chassis.Model.Blueridge1S4U.json.
> 
> below are the lines:
> 
> > auto configFileName = name + ".json";
> > auto configFilePath = fs::path{confBasePath} / configFileName;

we are not having any json change with this commit.

2024-07-09 11:50 UTC, PriyangaRamasamy approved these changes

2024-07-22 06:09 UTC, jinuthomas approved these changes

2024-07-22 06:09 UTC, merged