Fix miscellaneous LED grouping
ibm-openbmc/phosphor-led-manager pull request #8
Opened 2022-03-23 15:21 UTC by jinuthomas

added unique groups for each miscellaneous led

Signed-off-by: Jinu Joy Thomas <jinu.joy.thomas@in.ibm.com>

2022-03-24 09:22 UTC, jinuthomas commented
fixes SW546458 partially will also need https://github.ibm.com/openbmc/openbmc/pull/2088 to go in together

2022-03-24 14:06 UTC, santoshpuranik requested changes
Have some queries about the CXP ports and we'll need to propagate any changes to group names (and maybe even additions) to https://github.com/ibm-openbmc/pldm/tree/1020/oem/ibm/configurations/pdr

2022-03-24 14:06 UTC, santoshpuranik commented on configs/ibm,everest/led-group-config.json
> +         "group" : "c4_cxp_top_identify",
These already seem to be there as cablecard_* groups

2022-03-24 14:06 UTC, santoshpuranik commented on configs/ibm,rainier-1s4u/led-group-config.json
> +         "group" : "c0_cxp_top_identify",
Same with these - I think the cable card CXP ports have a physical LED, so I think we should not need these.

2022-03-25 12:33 UTC, santoshpuranik approved these changes

2022-03-28 03:45 UTC, merged